from typing import Dict, List, Any
from trip_types import TripPlan


def generate_itinerary_pdf(plan: TripPlan, destination: str, days: int) -> bytes:
    itinerary = plan.get("itinerary", [])
    budget = plan.get("budget", {})
    links = plan.get("links", {})

    html = _build_html(itinerary, budget, links, destination, days)

    try:
        from weasyprint import HTML
        return HTML(string=html).write_pdf()
    except ImportError:
        return _generate_text_pdf(itinerary, budget, links, destination, days)


def _build_html(
    itinerary: list, budget: dict, links: dict, destination: str, days: int
) -> str:
    rows = ""
    for i, day in enumerate(itinerary, 1):
        rows += f"<tr><td>{i}</td><td>{day}</td></tr>\n"

    budget_rows = ""
    for k, v in budget.items():
        budget_rows += f"<tr><td>{k.capitalize()}</td><td>₹{v}</td></tr>\n"

    links_html = ""
    booking = links.get("booking", {})
    if isinstance(booking, dict):
        for k, v in booking.items():
            links_html += f"<li><a href='{v}'>{k.replace('_', ' ').title()}</a></li>\n"
    if links.get("maps_search"):
        links_html += f"<li><a href='{links['maps_search']}'>Google Maps</a></li>\n"

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"/><title>{destination} Trip Plan</title>
<style>
body {{ font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: auto; }}
h1 {{ color: #2563eb; }}
h2 {{ color: #1e40af; border-bottom: 2px solid #93c5fd; padding-bottom: 4px; }}
table {{ border-collapse: collapse; width: 100%; margin: 10px 0; }}
th, td {{ border: 1px solid #d1d5db; padding: 8px; text-align: left; }}
th {{ background: #f3f4f6; }}
ul {{ padding-left: 20px; }}
.footer {{ margin-top: 30px; color: #6b7280; font-size: 12px; }}
</style></head><body>
<h1>✈️ {destination} Travel Itinerary ({days} Days)</h1>
<h2>Day-wise Plan</h2>
<table><tr><th>Day</th><th>Activities</th></tr>{rows}</table>
<h2>Budget Breakdown</h2>
<table><tr><th>Category</th><th>Amount</th></tr>{budget_rows}</table>
<h2>Booking Links</h2>
<ul>{links_html}</ul>
<p class="footer">Generated by AI Travel Planner Agent</p>
</body></html>"""


def _generate_text_pdf(
    itinerary: list, budget: dict, links: dict, destination: str, days: int
) -> bytes:
    import json
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas
    import tempfile
    import os

    fd, path = tempfile.mkstemp(suffix=".pdf")
    os.close(fd)
    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4
    y = height - 50

    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, f"Travel Itinerary: {destination} ({days} Days)")
    y -= 30

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Day-wise Plan")
    y -= 20
    c.setFont("Helvetica", 10)
    for i, day in enumerate(itinerary, 1):
        if y < 50:
            c.showPage()
            y = height - 50
        c.drawString(60, y, f"Day {i}: {day}")
        y -= 14

    y -= 20
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Budget Breakdown")
    y -= 20
    c.setFont("Helvetica", 10)
    for k, v in budget.items():
        c.drawString(60, y, f"{k.capitalize()}: \u20b9{v}")
        y -= 14

    c.showPage()
    c.save()

    with open(path, "rb") as f:
        data = f.read()
    os.unlink(path)
    return data
